spring:
  application:
    name: store-gateway

  cloud:
    routes:
      - id: store-auth
        uri: lb://store-auth
        predicates:
          - Path=/auth/**
        
      - id: insper
        uri: https://insper.edu.br
        predicates:
          - Path=/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: $(EUREKA_URI:http://localhost:8761/eureka/)